% testing fuzzy_gui
% 

% 01. Test default
bt = {'This is option one';...
	'another option'; ...
	'whatever you choose';...
	'is fine with this test';...
	'here the default settings';...
	'are not changed';...
	'bim bilim blom bam'};

fuzzy_gui(bt);