% solved it:
% for some reason 'linesmooting' was disabling WindowKeyPressFcn

% test for WindowKeyPressFcn
cpal = color_palette();
elec_color = mat2cell(cpal, ...
    ones(size(cpal,1), 1), 3);
nelec = size(EEG.data, 1);
rejmat = eeg_rejmat(EEG);
elec = 1:nelec;

eegplot2(EEG.data, 'srate', EEG.srate, 'color', ...
        elec_color, 'dispchans', nelec, 'eloc_file',...
        EEG.chanlocs(elec), 'events', EEG.event, 'winrej',...
        rejmat, 'tag', 'eegplot', 'wincolor', ...
        EEG.reject.rejmanualcol, 'butlabel', 'done',...
        'command', '', 'winlength', 5, 'limits', ...
        [EEG.times(1), EEG.times(end)], 'labels', ...
        EEG.reject.ICAw.name, 'labcol', ... 
        EEG.reject.ICAw.color, 'linesmoothing',...
        'off');
    
chld = get(gcf, 'Children');
tp = get(chld, 'type');
chld = chld(strcmp(tp, 'uicontrol'));
set(chld, 'KeyPressFcn', @eegplot_readkey_new)

addlistener(gcf, 'WindowKeyPress', @eegplot_readkey_new);

eegplot(EEG.data, 'srate', EEG.srate, 'color', ...
        elec_color, 'dispchans', nelec, 'eloc_file',...
        EEG.chanlocs(elec), 'events', EEG.event, 'winrej',...
        rejmat, 'tag', 'eegplot', 'wincolor', ...
        EEG.reject.rejmanualcol, 'butlabel', 'done',...
        'command', '', 'winlength', 5, 'limits', ...
        [EEG.times(1), EEG.times(end)]);
