function pth = db_test_temp_path(db, r, t)

temp = db(r).datainfo.tempfiles;
if temp(t).filepath(1) == '+'
	% this uses a vild path from db(r).filepath
	% and a subdir in it
	pth = get_valid_path(db(r).filepath, ...
		'file', temp(t).filename, ...
		'dir', temp(t).filepath(2:end), ...
		'noerror', true));
else
	pth = get_valid_path(temp(t).filepath, ...
		'file', temp(t).filename, ...
		'noerror', true));
end