eeglab_vars = {...
	'ALLCOM', ...                     
	'ALLEEG', ...                     
	'AXES_FONTSIZE', ...              
	'AXES_FONTSIZE_L', ...            
	'AXES_FONTSIZE_S', ...            
	'BACKCOLOR', ...                  
	'BACKEEGLABCOLOR', ...            
	'CURRENTSET', ...                 
	'CURRENTSTUDY', ...               
	'DEFAULT_COLORMAP', ...           
	'DEFAULT_ELOC', ...               
	'DEFAULT_EPOCH', ...              
	'DEFAULT_SRATE', ...              
	'DEFAULT_TIMLIM', ...             
	'EEG', ...                        
	'EEGOPTION_PATH', ...             
	'GUIBACKCOLOR', ...               
	'GUIBUTTONCOLOR', ...             
	'GUIPOPBUTTONCOLOR', ...          
	'GUITEXTCOLOR', ...               
	'GUI_FONTSIZE', ...
	'GUI_FONTSIZE_L', ...
	'GUI_FONTSIZE_S', ...
	'HZDIR', ...
	'ICABINARY', ...
	'LASTCOM', ...
	'MAXEEGPLOTCHANS', ...
	'MAXENVPLOTCHANS', ...
	'MAXPLOTDATACHANS', ...
	'MAXPLOTDATAEPOCHS', ...
	'MAXTOPOPLOTCHANS', ...
	'PLOT_LINEWIDTH', ...
	'PLOT_LINEWIDTH_S', ...
	'PLUGINLIST', ...
	'PLUGINMENUCOLOR', ...
	'SC', ...
	'SHRINKWARNING', ...
	'STUDY', ...
	'TEXT_FONTSIZE', ...
	'TEXT_FONTSIZE_L', ...
	'TEXT_FONTSIZE_S', ...
	'TUTORIAL_URL', ...
	'VERS', ...
	'YDIR', ...
};

clear(eeglab_vars{:});
clear option_* homefolder eeglabUpdater lowscreendepth eeglab_p res tmpp2 vartext oldp
clear eeglab_vars